name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: target/site/jacoco/jacoco.csv
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '0 100'



#      - name: Get code coverage
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          recreate: true
#          path: code-coverage-results.md

#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60